name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./UcnDomainDriven/
    - name: Build
      run: dotnet build --no-restore ./UcnDomainDriven/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./UcnDomainDriven/
    - name: Package NuGet
      run: dotnet pack --configuration release
    - name: Push Package to GitHub Packages
      run: dotnet nuget push "bin/Release/ucn.domain.1.0.0.nupkg"  --api-key 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 --source "github"
